version: '3.1'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    links:
      - db
    environment:
      - "DB_PORT=3307"
      - "DB_HOST=db"
      - "DB_NAME=klapp"
      - "DB_PASS=Password1"  
    volumes:
      - ./:/go/src/github.com/kylemlee/klapp
    working_dir: /go/src/github.com/kylemlee/klapp 
  
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      - "MYSQL_DATABASE=klapp"
      - "MYSQL_ROOT_PASSWORD=Password1"
      - "MYSQL_PASSWORD=Password1"